In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1) #랜덤의 결과가 일정하게 나오도록

In [2]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

print(x_train.shape)

torch.Size([3, 1])


- 가중치, 편향 초기화

In [3]:
W = torch.zeros(1,requires_grad=True) #학습을 통해 값이 변경되는 변수임을 명시
print(W)

tensor([0.], requires_grad=True)


In [4]:
b = torch.zeros(1,requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


- 가설 세우기
    - H(x) = Wx + b

In [5]:
hypo = x_train * W + b
print(hypo)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


- Loss Function
    - mse

In [7]:
cost = torch.mean((hypo - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


- Gradient Descnet

In [9]:
optimizer = optim.SGD([W,b],lr=0.01) 
# W,b가 SGD의 입력

    - optimizer.zero_grad()를 실행하면 미분을 통해 얻은 기울기를 0으로 초기화
    - 기울기를 초기화해야 새로운 가중치 편향에 대해서 새로운 기울기를 구한다.

    - cost.backward()를 호출하면 W,b에 대한 기울기가 계산된다.
    - optimizer.step()을 호출하면 인수로 들어간 W,b에서 리턴되는 변수들의 기울기 * lr을 곱하고 빼주면서 업데이트

In [11]:
# gradient를 0으로 초기화
optimizer.zero_grad()

# cost function을 미분하여 gradient계산
cost.backward()

# W와 b를 업데이트
optimizer.step()

## Final

In [13]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

W = torch.zeros(1,requires_grad=True)
b = torch.zeros(1,requires_grad=True)

optimizer = optim.SGD([W,b],lr=0.01)

nb_epochs = 499

for epoch in range(nb_epochs+1):

    # H(x) 계산
    hypo = x_train * W + b

    #cost 계산
    cost = torch.mean((hypo - y_train)**2)

    #cost로 H(x) 개선
    optimizer.zero_grad() #epoch마다 gradient가 누적되는것을 방지하기 위해
    cost.backward()
    optimizer.step()

    #100번마다 로그 출력
    if epoch % 100 ==0:
        print('Epoch {:4d}/{} W:{:.3f}, b:{:.3f} Cost: {:.6f}'.format(epoch,nb_epochs,W.item(),b.item(),cost.item()))

Epoch    0/499 W:0.187, b:0.080 Cost: 18.666666
Epoch  100/499 W:1.746, b:0.578 Cost: 0.048171
Epoch  200/499 W:1.800, b:0.454 Cost: 0.029767
Epoch  300/499 W:1.843, b:0.357 Cost: 0.018394
Epoch  400/499 W:1.876, b:0.281 Cost: 0.011366
