## Pytorch에서 미리 구현해놓은 함수
- nn.Linear()
- nn.functional.mse_loss()

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

model = nn.Linear(input_dim,output_dim)
cost = F.mse_loss(prediction,y_train)

In [2]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [9]:
print(x_train.ndim)
print(y_train.ndim)

2
2


In [10]:
model = nn.Linear(1,1)
# 하나의 입력에 대해서 하나의 출력
# model에는 가중치와 편향이 저장되어있다.
# model.parameters() 로 불러올 수 있다.

In [11]:
print(list(model.parameters())) # 랜덤 초기화된 값

[Parameter containing:
tensor([[0.8742]], requires_grad=True), Parameter containing:
tensor([0.3112], requires_grad=True)]


In [12]:
optimizer = optim.SGD(model.parameters(),lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs+1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f'epoch : {epoch}/{nb_epochs} cost : {cost.item()}')

epoch : 0/1000 cost : 4.610449314117432
epoch : 100/1000 cost : 0.040472596883773804
epoch : 200/1000 cost : 0.025009578093886375
epoch : 300/1000 cost : 0.015454384498298168
epoch : 400/1000 cost : 0.009549885988235474
epoch : 500/1000 cost : 0.005901244003325701
epoch : 600/1000 cost : 0.003646592376753688
epoch : 700/1000 cost : 0.0022533771116286516
epoch : 800/1000 cost : 0.0013924489030614495
epoch : 900/1000 cost : 0.000860454689245671
epoch : 1000/1000 cost : 0.0005317089380696416


## Test

In [13]:
new_var = torch.FloatTensor([[4.0]])

pred_y = model(new_var)

print(f'결과 값 : {pred_y}')

결과 값 : tensor([[7.9539]], grad_fn=<AddmmBackward0>)


In [14]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9733]], requires_grad=True), Parameter containing:
tensor([0.0607], requires_grad=True)]


---

## 다중 선형회귀

In [15]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [16]:
X_train = torch.FloatTensor([
    [73,80,75],
    [93,88,93],
    [89,91,90],
    [96,98,100],
    [73,66,70]
])

y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [17]:
print(X_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [18]:
model = nn.Linear(X_train.shape[1],y_train.shape[1])

print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [19]:
optimizer = optim.SGD(model.parameters(),lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs+1):

    prediction = model(X_train)

    cost = F.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f'epoch : {epoch}/{nb_epochs} cost : {cost.item()}')


epoch : 0/1000 cost : 31667.599609375
epoch : 100/1000 cost : 0.2259877622127533
epoch : 200/1000 cost : 0.22390875220298767
epoch : 300/1000 cost : 0.22193531692028046
epoch : 400/1000 cost : 0.22005856037139893
epoch : 500/1000 cost : 0.21826967597007751
epoch : 600/1000 cost : 0.2165713608264923
epoch : 700/1000 cost : 0.2149544209241867
epoch : 800/1000 cost : 0.21341824531555176
epoch : 900/1000 cost : 0.2119542360305786
epoch : 1000/1000 cost : 0.2105575054883957


In [20]:
new_var = torch.FloatTensor([[73,80,75]])

pred_y = model(new_var)

print(pred_y)

tensor([[151.1757]], grad_fn=<AddmmBackward0>)


In [21]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9818, 0.4454, 0.5812]], requires_grad=True), Parameter containing:
tensor([0.2796], requires_grad=True)]
