In [1]:
import torch
import numpy as np

### tensor 만들기

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [5]:
t = torch.tensor(np_array)
t

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

### ones_like, rand_like

In [6]:
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data,dtype=torch.float)

print(x_ones)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.9800, 0.2887],
        [0.0807, 0.8114]])


### shape으로 tensor만들기

In [7]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.8913, 0.0235, 0.0911],
        [0.9023, 0.1011, 0.8531]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### tensor의 attributes

In [8]:
tensor = torch.rand(3,4)

print(f'Shape of tensor : {tensor.shape}')
print(f'DataType of tensor : {tensor.dtype}')
print(f'Device tensor is stored on : {tensor.device}')

Shape of tensor : torch.Size([3, 4])
DataType of tensor : torch.float32
Device tensor is stored on : cpu


### GPU 사용하기

In [9]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f'Device tensor is stored on : {tensor.device}')

Device tensor is stored on : cuda:0


### slicing

In [10]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


### concatenate

In [11]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


### tensor 곱하기

In [13]:
# element-wise product
print(f'tensor.mul(tensor) \n {tensor.mul(tensor)} \n')
print(f'tensor * tensor \n {tensor * tensor}')

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [16]:
#내적
print(f'tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n')
print(f'tnesor @ tensor.T \n {tensor @ tensor.T}')

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tnesor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


### numpy 사용하기

In [17]:
t = torch.ones(5)
print(f't: {t}')
n = t.numpy()
print(f'n: {n}')

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


#### torch tensor의 변화는 numpy 행렬도 반영된다.

In [19]:
t.add_(1)
print(f't:{t}')
print(f'n:{n}')

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]


### numpy array -> tensor

#### numpy array의 변화는 tensor 행렬에도 반영된다.

In [20]:
n = np.ones(5)
t = torch.from_numpy(n)

np.add(n,1,out=n)
print(f't:{t}')
print(f'n: {n}')

t:tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
