## PyTorch Tensor

In [3]:
import torch

t = torch.FloatTensor([1,2,3,4])

print(t)
print(f'Rank of t : {t.ndim}')
print(f'Shape of t : {t.shape}')

tensor([1., 2., 3., 4.])
Rank of t : 1
Shape of t : torch.Size([4])


### Slicing

In [4]:
print(t[0])
print(t[2:5])
print(t[:2])

tensor(1.)
tensor([3., 4.])
tensor([1., 2.])


### Mean

In [5]:
print(t.mean())

tensor(2.5000)


## View
- 원소의 수를 유지하면서 텐서의 크기를 변경
- numpy의 reshape과 같은 역할

In [6]:
t = np.array([[[0,1,2],\
    [3,4,5]],\
    [[6,7,8],\
    [9,10,11]]])

ft = torch.FloatTensor(t) # torch tensor 생성

print(ft.shape)

torch.Size([2, 2, 3])


In [7]:
print(ft.view([-1,3])) # (?,3)으로 변경
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


## Squeeze
- 1인 차원을 제거

In [17]:
ft = torch.FloatTensor([[0],[1],[2]])

print(ft)
print(ft.shape)

ft2 = ft.view([3,1,1])
print(ft2)
print(ft2.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[[0.]],

        [[1.]],

        [[2.]]])
torch.Size([3, 1, 1])


In [18]:
print(ft.squeeze())
print(ft.squeeze().shape)

print(ft2.squeeze())
print(ft2.squeeze().shape) # 1인 차원이 2개여도 모두 제거

tensor([0., 1., 2.])
torch.Size([3])
tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze
- 특정 위치에 1인 차원을 추가

In [20]:
ft = torch.Tensor([0,1,2])
print(ft.shape)
print(ft.ndim)

torch.Size([3])
1


In [23]:
print(ft.unsqueeze(0)) #0번째 차원에 1인 차원을 추가
print(ft.unsqueeze(0).shape)
print(ft.unsqueeze(0).ndim) #1차원이 2차원으로 증가

tensor([[0., 1., 2.]])
torch.Size([1, 3])
2


In [25]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)
print(ft.view(1,-1).ndim)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
2


### Type Casting

In [28]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [29]:
print(lt.float())

tensor([1., 2., 3., 4.])


### Concatenate

In [30]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [31]:
print(torch.cat([x,y],dim=0))

print(torch.cat([x,y],dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [32]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [36]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


- 아래의 연산을 한번에 해준 것

In [35]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### In-plack Operation
- 덮어쓰기 연산 _

In [37]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x)

# 연산이 반영되지 않는다.

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [38]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
