In [1]:
import torch

x = torch.rand(2,3)
print(x)

tensor([[0.2125, 0.3717, 0.9471],
        [0.2216, 0.4860, 0.9231]])


In [2]:
import numpy as np

t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('rank of t : ',t.ndim)
print('shape of t: ',t.shape)

rank of t :  1
shape of t:  (7,)


In [5]:
print('t[0] t[1] t[-1] = ',t[0],t[1],t[-1])
print('t[2:5] t[4:-1] = ',t[2:5],t[4:-1])
print('t[:2] t[3:] = ',t[:2],t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [6]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [7]:
print('rank of t : ',t.ndim)
print('shape of t : ',t.shape)

rank of t :  2
shape of t :  (4, 3)


In [10]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [12]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[3:])


1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [17]:
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [16]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[:,1])
print(t[:,1].size())
print(t[:,:-1])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [38]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [37]:
n = np.array([3,3])
print(n)
print(n.ndim)
print(n.shape)
print()
n1 = np.array([[3,3]])
print(n1)
print(n1.ndim)
print(n1.shape)

[3 3]
1
(2,)

[[3 3]]
2
(1, 2)


In [40]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])
print(m1+m2)

tensor([[4., 5.]])


In [41]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [42]:
print()
print('-------------')
print('Mul vs MatMul')
print('-------------')
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ',m1.shape)
print('Shape of Matrix 2: ',m2.shape)
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1: ',m1.shape)
print('Shape of Matrix 2: ',m2.shape)
print(m1 * m2)
print(m1.mul(m2))


-------------
Mul vs MatMul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [43]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [45]:
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exe:
    print(exe)

Can only calculate the mean of floating types. Got Long instead.


In [46]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [48]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [49]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [50]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [62]:
t = torch.FloatTensor([[1,4],[4,3]])
print(t)

tensor([[1., 4.],
        [4., 3.]])


In [63]:
print(t.max())

tensor(4.)


In [64]:
print(t.max(dim=0))
print('Max : ',t.max(dim=0)[0])
print('Argmax : ',t.max(dim=0)[1])

torch.return_types.max(
values=tensor([4., 4.]),
indices=tensor([1, 0]))
Max :  tensor([4., 4.])
Argmax :  tensor([1, 0])


In [65]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([4., 4.]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([4., 4.]),
indices=tensor([1, 0]))
