### Multi-class Classification
- 세개 이상의 답 중 하나를 고르는 문제
- 확률의 총합이 1이되는 아이디어
- 각 클래스, 즉 선택지마다 소수확률을 할당
- 선택지의 개수만큼의 차원을 가지는 벡터를 만든다.
- H(x) = softmax(WX + B)
- Cost : CrossEntropy

#### Cost Fucntion
##### Cross Entropy

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [3]:
z = torch.FloatTensor([1,2,3])

h = F.softmax(z,dim=0)
print(h)

tensor([0.0900, 0.2447, 0.6652])


In [4]:
h.sum()

tensor(1.)

- 직접 구현

In [5]:
z = torch.rand(3,5,requires_grad=True) # 3x5 행렬 생성

h = F.softmax(z,dim=1)
print(h)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [6]:
# label 생성
y = torch.randint(5,(3,)).long()
print(y)

tensor([0, 2, 1])


In [7]:
# one-hot encoding
y_one_hot = torch.zeros_like(h)
y_one_hot.scatter_(1,y.unsqueeze(1),1) # (3,1)로 만들어주기
# scatter : 첫번째 dim=1에 대해서 수행 / 세번째 두번째인자가 알려주는 위치에 1채우기

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [8]:
cost = (y_one_hot * -torch.log(h)).sum(dim=1).mean()
cost 

tensor(1.4689, grad_fn=<MeanBackward0>)

- Pytorch로 구현하기
    - F.softmax() + torch.log() = F.log_softmax()

In [9]:
F.log_softmax(z,dim=1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward0>)

- F.log_softmax() + F.nll_loss = F.cross_entropy()
    - F.nll_loss : 원핫벡터를 넣을 필요없이 실제값을 인자로 사용
    - nagative log likelihood

In [10]:
F.cross_entropy(z,y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

### cross entropy에 softmax까지 포함하고 있음을 기억해야한다.