In [1]:
import numpy as np
import mnist
np.random.seed(42)

In [9]:
X_train,y_train = mnist.train_images(),mnist.train_labels()
X_test, y_test = mnist.test_images(),mnist.test_labels()
num_classes = 10 
#클래스는 0~9까지 숫자

#이미지를 column 벡터(NN의 입력)으로 변환
X_train,X_test = X_train.reshape(-1,28*28),X_test.reshape(-1,28*28)

#레이블을 원핫벡터로 변환
#[0,0,0,0,1,0,0,0,0,0]
y_train = np.eye(num_classes)[y_train]

In [7]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [8]:
b=[5,4,3]

a = np.eye(10)[b]
a

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

## 네트워크 구성하기

In [10]:
import numpy as np


class FullyConnectedLayer(object):
    def __init__(self,num_inputs, layer_size, activation_fn):
        super().__init__()
        self.W = np.random.standard_normal((num_inputs,layer_size))
        self.b = np.random.standard_normal(layer_size)
        self.activation_fn = activation_fn
        self.size = layer_size
        
    def forward(self,x):
        z = np.dot(x,self.W) + self.b
        return self.activation_fn(z)
    
    

In [18]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

class SimpleNetwork(object):
    """
    Args:
        num_inputs(int) : 입력벡터크기 / 입력 값 개수
        num_outpus(int) : 출력 벡터 크기
        hidden_layers_sizes(list) : 네트워크에 추가될 은닉 계층의 크기를 포함한 리스트
        
    Attributes:
        layers(list) : 이 간단하 네트워크를 구성하는 계층 리스트
    """
    
    def __init__(self,num_inputs,num_outputs,hidden_layers_sizes=(64,32)):
        super().__init__()
        sizes = [num_inputs, *hidden_layers_sizes,num_outputs]
        self.layers = [
            FullyConnectedLayer(sizes[i],sizes[i+1],sigmoid)
            for i in range(len(sizes)-1)
        ]
        
    def forward(self,x):
        """
        x에 대응하는 출력을 계산하고 출력값이 가장 큰 인덱스를 반환
        """
        for layer in self.layers:
            x = layer.forward(x)
        return x
    
    def predict(self,x):
        estimations = self.forward(x)
        best_class = np.argmax(estimations)
        return best_class
    
    def evaluate_accuracy(self,X_val,y_val):
        num_corrects = 0
        for i in range(len(X_val)):
            if self.predict(X_val[i]) == y_val[i]:
                num_corrects += 1
        return num_corrects / len(X_val)

In [19]:
X_train.shape

(60000, 784)

In [21]:
mnist_classifier = SimpleNetwork(X_train.shape[1],num_classes,[64,32])
mnist_classifier.forward(X_train)

/var/folders/my/lj1l_34s0hs5sp6zrt4030wm0000gn/T/ipykernel_12660/2655457516.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


array([[0.93269358, 0.00610164, 0.99282155, ..., 0.86261218, 0.35787102,
        0.90615434],
       [0.58505329, 0.01057523, 0.99532156, ..., 0.9024037 , 0.13394289,
        0.8126381 ],
       [0.96325884, 0.0038867 , 0.98285192, ..., 0.97967006, 0.05913087,
        0.94243247],
       ...,
       [0.85649389, 0.01351213, 0.97573045, ..., 0.66947026, 0.01510557,
        0.86794212],
       [0.82078596, 0.0085065 , 0.99857337, ..., 0.81036765, 0.00134269,
        0.54341509],
       [0.60540594, 0.00711165, 0.99455486, ..., 0.94868402, 0.04011231,
        0.32078214]])

In [23]:
mnist_classifier.predict(X_train)

/var/folders/my/lj1l_34s0hs5sp6zrt4030wm0000gn/T/ipykernel_12660/2655457516.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


442452

In [24]:
accuracy = mnist_classifier.evaluate_accuracy(X_test,y_test)

/var/folders/my/lj1l_34s0hs5sp6zrt4030wm0000gn/T/ipykernel_12660/2655457516.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


In [26]:
accuracy * 100

10.36